title: notebook
email:
description: >- 
  Engineering concepts. Fun stuff.
github_username: twydev
minimal_mistakes_skin: "dark"
search: true
logo: "/assets/images/nlogo40.png"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/
timezone: Asia/Singapore 

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "twydev"
  avatar : "/assets/images/penguin.png"
  location: "Singapore"
  bio    : "Hi"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/twydev/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://sg.linkedin.com/in/wei-yang-tan"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/twydev/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://sg.linkedin.com/in/wei-yang-tan"

collections:
  lifestyle:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _lifestyle
  - scope:
      path: ""
      type: lifestyle
    values:
      layout: single
      read_time: false
      author_profile: true
      comments: false
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/